[[missions]]
id = 23
name = "Investigate the Ruins"
dialog = "<h2>Mission Briefing: Investigate the ruins</h2><br>Commander, we’ve detected unusual energy signatures in the nearby ruins. Your objective is to investigate the site, collect three energy crystals, and return safely.<br>Beware — hostile entities may be present.<br><br><h3>Mission Objectives</h3><br>1. Investigate site<br>2. Collect energy crystals.<br>3. Return to NPC (because I'm self-aware that this is a game, strangely)."
objectives = []

[[missions]]
id = 612
name = "sdfdsf"
dialog = "diaaaaalog"
objectives = []
